### ISSUE TITLE
What are "Reports" and "Blocks"?

### ISSUE THREAD

**Issue by jankeromnes** [adngdb/processeer#2]
I think there is a low-hanging fruit in terms of quickly showing newcomers what processeer does.

On the front page, there are two sections, "All Reports" and "All Blocks", but as a newcomer I have no idea what these are. Maybe we could add a single, short sentence under each section title to briefly explain what these are? For example:

## All Blocks

_Blocks are [...] that [...] in your [...]._

(Or more discreet: You could add a round "?" icon next to "All Blocks" that reveals this sentence as a tooltip.)

**Comment by adngdb** [comment]
I've added a link to the README of this repo, which contains some explanations about what blocks and reports are. The idea of adding a help icon is good though, I'll do that at some point.
